POST http://localhost:5028/api/roles
Content-Type: application/json

{
    "id": 0,
    "name": "SuperAdmin",
    "description": "Super Admin",
    "roleEnum": 1000
}

###

POST http://localhost:5028/api/roles
Content-Type: application/json

{
    "id": 0,
    "name": "SuperAdmin",
    "description": "Super Admin",
    "roleEnum": 1000
}
