@host_address =  http://localhost:5028/api
@jwt_token = 

###

GET {{host_address}}/roles
Accept: application/json
Authorization: Bearer {{jwt_token}}

###

POST {{host_address}}/roles
Content-Type: application/json

{
    "id": 0,
    "name": "SuperAdmin",
    "description": "Super Admin",
    "roleEnum": 1000
}

###

POST {{host_address}}/roles
Content-Type: application/json

{
"id": 0,
"name": "Admin",
"description": "Admin",
"roleEnum": 1001
}

###

POST {{host_address}}/roles
Content-Type: application/json

{
  "id": 0,
  "name": "User",
  "description": "User",
  "roleEnum": 2000
}

###
GET {{host_address}}/roles/5
Content-Type: application/json